// priority: 9
onEvent('recipes', event => {
	event.remove({ id:'ftbquests:loot_crate_opener'})
	event.remove({ output: AE2('vibration_chamber') })
	event.remove({ output: AE2('inscriber') })
	event.remove({ output: AE2('quartz_glass') })
	event.remove({ input: '#forge:coins' })
	event.remove({ type: TE('press') })
	event.remove({ id: /thermal:earth_charge\/.*/ })
	event.remove({ id: /thermal:machines\/smelter\/.*dust/ })
	event.remove({ id: /tconstruct:smeltery\/.*\/ore/ })
	event.remove({ id: "tconstruct:tables/tinkers_forge" })
	event.remove({ id: "tconstruct:tables/scorched_forge" })
	event.remove({ id: /tconstruct:smeltery\/.*\/coin.*/ })
	event.remove({ id: /tconstruct:smeltery\/.*\/tin.*/ })
	event.remove({ id: /ae2:tools\/paintballs.*/ })
	event.remove({ id: "grapplemod:repeller" })
	event.remove({ id: "grapplemod:forcefieldupgradeitem" })
	event.remove({ id: "grapplemod:rocketupgradeitem" })
	event.remove({ id: "grapplemod:rocketdoublemotorhook" })
	event.remove({ id: "grapplemod:magnethook" })
	event.remove({ id: "grapplemod:rockethook" })
	event.remove({ id: "forbidden_arcanus:eternal_stella" })
	event.remove({ id: MC('diorite') })
	event.remove({ id: MC('andesite') })
	event.remove({ id: MC('granite') })
	event.remove({ id: TC('smeltery/melting/metal/gold/enchanted_apple') })
	event.remove({ id: CR('cutting/andesite_alloy') })
	event.remove({ id: QU('building/crafting/compressed/charcoal_block')})
	event.remove({ id: QU('building/crafting/compressed/sugar_cane_block')})
	event.remove({ id: QU('building/crafting/compressed/gunpowder_sack')})
	event.remove({ id: QU('building/crafting/compressed/apple_crate')})
	event.remove({ id: QU('building/crafting/compressed/potato_crate')})
	event.remove({ id: QU('building/crafting/compressed/carrot_crate')})
	event.remove({ id: QU('building/crafting/compressed/beetroot_crate')})
	event.remove({ id: TE('building/crafting/compressed/bamboo_block')})
	event.remove({ id: TE('storage/carrot_block') })
	event.remove({ id: TE('storage/potato_block') })
	event.remove({ id: TE('storage/beetroot_block') })
	event.remove({ id: AE2('misc/grindstone_woodengear') })
	event.remove({ id: AE2('tools/misctools_entropy_manipulator') })
	event.remove({ id: AP('smelting/charcoal_block_from_logs_that_burn_smoking') })
	event.remove({ id: 'portality:generator' })

	event.remove({ id: TE('machines/pulverizer/pulverizer_cinnabar') }) //Overlaps with the redstone recipe
	event.remove({ id: TE('machines/pulverizer/pulverizer_ender_pearl') }) //should have output replaced instead

	event.remove({ mod: 'portable_stonecutter' })
	event.remove({ mod: 'explorerscompass' })
	event.remove({ mod: 'extendedgears' }) //The recipes from this mod are pretty disgusting
	event.remove({ output: TE('lightning_charge') })
	event.remove({ output: TE('ice_charge') })
	event.remove({ output: TE('earth_charge') })
	event.remove({ input: TE('lightning_charge') })
	event.remove({ input: TE('ice_charge') })
	event.remove({ input: TE('earth_charge') })
	event.remove({ input: "forbidden_arcanus:edelwood_bucket" })
	event.remove({ output: "forbidden_arcanus:edelwood_bucket" })
	event.remove({ id: 'ravencoffee:croissant' })
	event.remove({ input: 'ravencoffee:croissant' })
	event.remove({ id: 'ravencoffee:bagel' })
	event.remove({ input: 'ravencoffee:bagel' })
	event.remove({ id: 'ravencoffee:melon_pan' })
	event.remove({ id: 'ravencoffee:muffin' })
	event.remove({ id: 'ravencoffee:popchorus' })
	event.remove({ id: 'ravencoffee:sandwich_ham' })
	event.remove({ id: 'ravencoffee:sandwich_beef' })
	event.remove({ id: 'ravencoffee:sandwich_chicken' })
	//Remove Tconstruct cheese since it only costs milk to craft and cheese already exists on the moon.
	event.remove({ id: TC('smeltery/casting/cheese_block')})
	event.remove({ id: TC('smeltery/casting/cheese_ingot_gold_cast')})
	event.remove({ id: TC('smeltery/casting/cheese_ingot_sand_cast')})
})