//for some inexplicable reason these need to be kept in seperate onEvent triggers.
//I've been told that this is some Rino (compiler) jank
onEvent('item.tags', event => {
	global.itemBlacklist.forEach(item=>{
		if (Item.exists(item)) {
			event.add('randomium:blacklist', item)
		} else {
			console.warn(`Failed to add \"randomium:blacklist\" tag to ${item} from randomium blacklist`)
		}
	})
})
onEvent('item.tags', event => {
	global.randomiumBlacklist.forEach(item=>{
		if (Item.exists(item)) {
			event.add('randomium:blacklist', item)
		} else {
			console.warn(`Failed to add \"randomium:blacklist\" tag to ${item} from randomium blacklist`)
		}
	})
})

onEvent('item.tags', event => {

	event.add('forge:dusts/obsidian', 'create:powdered_obsidian')
	event.add('forge:dusts', 'create:powdered_obsidian')

	//Fixes copper dupe.
	event.remove('forge:storage_blocks/copper', 'minecraft:cut_copper');

	colours.forEach(element => {
		event.get(F('glazed_terracotta')).add(MC(`${element}_glazed_terracotta`))
	});

	global.trades.forEach(element => {
		event.get('kubejs:transaction_cards/import').add(`kubejs:trade_card_${element}`)
	});

	global.professions.forEach(element => {
		event.get('kubejs:transaction_cards/profession').add(`kubejs:profession_card_${element}`)
	});

	event.get("farmersdelight:offhand_equipment").add("forbidden_arcanus:obsidian_skull_shield")
	
	unregistered_axes.forEach(axe => {
		event.get("forge:tools/axes").add(axe)
	});
	
	event.get("forge:vines").add(MC("vine"))

	event.get('forge:mushrooms')
		.add(EXP('sweetshroom')).add(EXP('goldishroom')).add(EXP('shinyshroom'))
		.add(EXP('lumishroom')).add(EXP('fluoshroom')).add(EXP('rockshroom'))
		.add('quark:glow_shroom')

	//These items aren't obtainable at the moment.
	//This tag lets these items be melted into iron using the smeltery
	event.get("kubejs:recycling/iron")
		.add("expcaves:rusty_pickaxe")
		.add("expcaves:rusty_sword")
		.add("expcaves:iron_dagger")
		.add("expcaves:gourmet_spoon")
		.add("expcaves:gourmet_fork")
		.add("expcaves:chef_knife")
		.add("expcaves:butcher_knife")

	//This tag lets these items be turned into circuit scraps and be melted into invar
	event.get("kubejs:circuit_press")
		.add(AE2("name_press"))
		.add(AE2("silicon_press"))
		.add(AE2("logic_processor_press"))
		.add(AE2("engineering_processor_press"))
		.add(AE2("calculation_processor_press"))
		.add('kubejs:circuit_scrap')

	event.get("forbidden_arcanus:modifier/eternal_incompatible")
		.add(/exchangers:.*/)
		.add(/reliquary:.*/)
		.add(/waterstrainer:.*/)
		.add(OC("#miners/ores"))
		.add(PR_C("draw_plate"))
		.add(PR_C("multimeter"))

	//crafting tools for the chapters
	event.get('kubejs:saws').add('cb_microblock:stone_saw').add('cb_microblock:iron_saw').add('cb_microblock:diamond_saw')
	event.get('kubejs:screwdrivers').add(PR_C('screwdriver'))
	event.get('kubejs:chromatic_resonators').add(KJ('chromatic_resonator'))
	event.get('kubejs:flash_drives').add(KJ('flash_drive'))

	event.get('kubejs:transaction_cards').add('#kubejs:transaction_cards/import')
	event.get('kubejs:transaction_cards').add('#kubejs:transaction_cards/profession')

	//This tag prevents items from being consumed in press (market) recipes
	event.get('thermal:crafting/dies').add('#kubejs:transaction_cards')
	event.get('thermal:crafting/dies').add('kubejs:missingno')

	event.get('thermal:crafting/casts').add(KJ("three_cast")).add(KJ("eight_cast")).add(KJ("plus_cast")).add(KJ("minus_cast")).add(KJ("multiply_cast")).add(KJ("divide_cast")).add(KJ("#circuit_press"))
	event.get('tconstruct:crafting/casts').add(TC('nugget_cast')).add(TC('ingot_cast')).add(TC('gem_cast')).add(TC('rod_cast')).add(TC('repair_kit_cast')).add(TC('plate_cast')).add(TC('gear_cast')).add(TC('wire_cast')).add(TC('pick_head_cast')).add(TC('small_axe_head_cast')).add(TC('small_blade_cast')).add(TC('hammer_head_cast')).add(TC('broad_blade_cast')).add(TC('broad_axe_head_cast')).add(TC('tool_binding_cast')).add(TC('round_plate_cast')).add(TC('large_plate_cast')).add(TC('tool_handle_cast')).add(TC('bow_grip_cast')).add(TC('bow_limb_cast')).add(TC('tough_handle_cast'))
	event.get('kubejs:casts')
		.add('#thermal:crafting/casts')
		.add('#tconstruct:crafting/casts')

	//Tags for use in market recipes	
		event.get('kubejs:food_crate')
			.add('quark:golden_apple_crate') 
			.add('quark:potato_crate') 
			.add('quark:carrot_crate') 
			.add('quark:beetroot_crate') 
			.add('farmersdelight:carrot_crate') 
			.add('farmersdelight:potato_crate') 
			.add('farmersdelight:beetroot_crate') 
			.add('farmersdelight:cabbage_crate') 
			.add('farmersdelight:tomato_crate') 
			.add('farmersdelight:onion_crate') 
			.add('farmersdelight:rice_bag')
			.add('thermal:apple_block') 
			.add('thermal:carrot_block') 
			.add('thermal:potato_block') 
			.add('thermal:beetroot_block') 
			.add('quark:apple_crate') 
			.add('buddycardsexp:buddybean_crate')
			.add('quark:glowberry_sack')
			.add('quark:berry_sack')
			.add('quark:chorus_fruit_block')
		event.get('market:export/farming')	
			.add(KJ('#food_crate'))
			.add(FD('canvas'))
			.add(F('#berries'))
			.add(MC('cocoa_beans'))
			.add(MC('honey_bottle'))
			.add(MC('honeycomb'))
			.add(MC('#small_flowers'))
			.add(MC('bread'))
			.add(F('#mushrooms'))
			.add(MC('kelp'))
			.add(MC('pumpkin'))
			.add(MC('#wool'))
			.add(MC('melon'))
			.add('kubejs:profession_card_farming')
		
		event.get('market:export/wood/1')
			.add(MC('oak_log'))
			.add(MC('spruce_log'))
			.add(MC('jungle_log'))
			.add(MC('dark_oak_log'))
			.add(BOP('redwood_log'))
			.add(BOP('fir_log'))
			.add(BOP('umbran_log'))
			.add(BOP('dead_log'))
		event.get('market:export/wood/2')
			.add(MC('acacia_log'))
			.add(MC('birch_log'))
			.add(BOP('cherry_log'))
			.add(TC('skyroot_log'))
			.add(TC('greenheart_log'))
			.add('architects_palette:twisted_log')
			.add('biomesoplenty:jacaranda_log')
		event.get('market:export/wood/3')
			.add(BOP('willow_log'))
			.add(BOP('palm_log'))
			.add(BOP('mahogany_log'))
			.add(BOP('magic_log'))
			.add('quark:azalea_log')
			.add('quark:blossom_log')
		event.get('market:export/wood/4')
			.add(MC('crimson_stem'))
			.add(MC('warped_stem'))
			.add(TC('bloodshroom_log'))
		event.get('market:export/carpentry')
			.add('#market:export/wood/1')
			.add('#market:export/wood/2')
			.add('#market:export/wood/3')
			.add('#market:export/wood/4')
			.add(BOP('hellbark_log'))
			.add('kubejs:profession_card_carpentry')

		event.get('market:export/stone/1')
			.add('minecraft:andesite') 
			.add('minecraft:granite') 
			.add('minecraft:diorite') 
			.add('minecraft:sandstone') 
			.add('create:limestone') 
			.add('create:scoria') 
		event.get('market:export/crushed_raw_ores/8')
			.add(CR('crushed_raw_iron'))
			.add(CR('crushed_raw_copper'))
			.add(CR('crushed_raw_zinc'))
		event.get('market:export/crushed_raw_ores/12')
			.add(CR('crushed_raw_nickel'))
			.add(CR('crushed_raw_lead'))
		event.get('market:export/stone/6')
			.add(TE('cinnabar'))
			.add(TE('sulfur'))
			.add(TE('niter'))
			.add(MC('lapis_lazuli'))
		event.get('market:export/gem/10')
			.add(TE('sapphire'))
			.add(TE('ruby'))
		event.get('market:export/mining')
			.add('#market:export/crushed_raw_ores/8')
			.add('#market:export/crushed_raw_ores/12')
			.add('create:crushed_raw_gold')
			.add('#market:export/stone/1')
			.add('#market:export/stone/6')
			.add('#market:export/gem/10')
			.add(MC('coal'))
			.add(TE('apatite'))
			.add(MC('diamond'))
			.add('kubejs:profession_card_mining')

		event.get('market:export/brick/4')
			.add(SP('checker_block'))
			.add(AP('olivestone_bricks'))
			.add(AP('flint_tiles'))
		event.get('market:export/brick/6')
			.add(AP('basalt_tiles'))
			.add(MC('bricks'))
			.add(TC('mud_bricks'))
			.add(AP('algal_bricks'))
			.add(AP('osseous_bricks'))
			.add(TC('lavawood'))
			.add(MC('mossy_cobblestone'))
			.add(F('#glazed_terracotta'))
		event.get('market:export/brick/8')
			.add(AP('packed_ice_pillar'))
			.add(AP('sunmetal_block'))
			.add(SP('daub_brace'))
		event.get('market:export/brick/10')
			.add(AP('gilded_sandstone'))
			.add(TC('seared_bricks'))
			.add(CR('ornate_iron_window'))
		event.get('market:export/masonry')
			.add('#market:export/brick/4')
			.add('#market:export/brick/6')
			.add('#market:export/brick/8')
			.add('#market:export/brick/10')
			.add(AP('abyssaline'))
			.add(MC('quartz_bricks'))
			.add('kubejs:profession_card_masonry')

		event.get('market:export/drop/5')
			.add(RQ('rib_bone'))
			.add(RQ('zombie_heart'))
			.add(RQ('chelicerae'))
			.add(RQ('nebulous_heart'))
			.add(RQ('molten_core'))
		event.get('market:export/drop/6')
			.add(RQ('slime_pearl'))
			.add(RQ('guardian_spike'))
		event.get('market:export/drop/8')
			.add(MC('phantom_membrane'))
			.add(MC('rabbit_foot'))
		event.get('market:export/drop/10')
			.add(RQ('bat_wing'))
			.add(MC('ghast_tear'))
			.add(RQ('catalyzing_gland'))
		event.get('market:export/drop/15')
			.add(RQ('witch_hat'))
			.add(RQ('withered_rib'))
		event.get('market:export/hunting')
			.add('#market:export/drop/5')
			.add('#market:export/drop/6')
			.add('#market:export/drop/8')
			.add('#market:export/drop/10')
			.add('#market:export/drop/15')
			.add(MC('dragon_breath'))
			.add(RQ('squid_beak'))
			.add(RQ('frozen_core'))
			.add(RQ('eye_of_the_storm'))
			.add(MC('nether_star'))
			.add(MC('dragon_egg'))
			.add('kubejs:profession_card_hunting')
		
		event.get('kubejs:cookies')
			.add(MC('cookie'))
			.add('farmersdelight:sweet_berry_cookie')
			.add(FD('honey_cookie'))
			.add('buddycardsexp:buddycookie')
		event.get('kubejs:cake_slices')
			.add(FD('cake_slice'))
		event.get('market:export/food/3')
			.add(AC('sushi'))
			.add(FD('apple_pie_slice'))
			.add(FD('bone_broth'))
			.add(FD('kelp_roll'))
			.add(FD('cod_roll'))
			.add(FD('salmon_roll'))
		event.get('market:export/food/4')
			.add(CR('bar_of_chocolate'))
			.add(CR('honeyed_apple'))
			.add(CR('builders_tea'))
			.add(FD('chocolate_pie_slice'))
			.add(CR('sweet_roll'))
		event.get('market:export/food/5')
			.add(FD('nether_salad'))
			.add(FD('cabbage_rolls'))
			.add(FD('hot_cocoa'))
			.add(FD('egg_sandwich'))
			.add(FD('apple_cider'))
			.add(FD('melon_juice'))
		event.get('market:export/food/6')
			.add(FD('barbecue_stick'))
			.add(FD('stuffed_potato'))
			.add(MC('pumpkin_pie'))
			.add(FD('glow_berry_custard'))
			.add(FD('bacon_and_eggs'))
			.add(FD('mushroom_rice'))
		event.get('market:export/food/7')
			.add(FD('melon_popsicle'))
			.add(FD('dumplings'))
			.add(FD('fruit_salad'))
			.add(MC('beetroot_soup'))
			.add(FD('roast_chicken'))
			.add(FD('honey_glazed_ham'))
			.add(FD('shepherds_pie'))
			.add(FD('grilled_salmon'))
		event.get('market:export/food/8')
			.add(FD('beef_stew'))
			.add(FD('fried_rice'))
		event.get('market:export/food/9')
			.add(FD('chicken_soup'))
			.add(FD('mixed_salad'))
			.add(FD('baked_cod_stew'))
			.add(FD('chicken_sandwich'))
			.add(FD('bacon_sandwich'))
			.add(FD('vegetable_soup'))
			.add(FD('fish_stew'))
			.add(FD('noodle_soup'))
			.add(FD('roasted_mutton_chops'))
			.add(FD('steak_and_potatoes'))
			.add(FD('stuffed_pumpkin'))
			.add(FD('ratatouille'))
		event.get('market:export/food/10')
			.add(FD('vegetable_noodles'))
			.add(FD('pasta_with_meatballs'))
			.add(FD('mutton_wrap'))
			.add(MC('rabbit_stew'))
			.add(FD('pasta_with_mutton_chop'))
		event.get('market:export/food/11')
			.add(FD('hamburger'))
			.add(FD('squid_ink_pasta'))
			.add(FD('pumpkin_soup'))
		event.get('market:export/cooking')
			.add('#market:export/food/3')
			.add('#market:export/food/4')
			.add('#market:export/food/5')
			.add('#market:export/food/6')
			.add('#market:export/food/7')
			.add('#market:export/food/8')
			.add('#market:export/food/9')
			.add('#market:export/food/10')
			.add('#market:export/food/11')
			.add('#kubejs:cookies')
			.add('#kubejs:cake_slices')
			.add(FD('tomato_sauce'))
			.add(SP('pancake'))
			.add(FD('sweet_berry_cheesecake_slice'))
			.add('kubejs:profession_card_cooking')

		event.get('market:export/fish/1')
			.add(MC('cod'))
			.add(MC('salmon'))
			.add(MC('tropical_fish'))
			.add(MC('pufferfish'))
		event.get('market:export/fish/3')
			.add(AC('atlantic_herring'))
			.add(AC('synodontis'))
			.add(AC('bluegill'))
			.add(AC('perch'))
			.add(AC('tambaqui'))
			.add(AC('minnow'))
			.add(AC('blackfish'))
		event.get('market:export/fish/5')
			.add(AC('pink_salmon'))
			.add(AC('brown_trout'))
			.add(AC('carp'))
			.add(AC('pollock'))
			.add(AC('smallmouth_bass'))
			.add(AC('boulti'))
			.add(AC('red_shrooma'))
			.add(AC('brown_shrooma'))
		event.get('market:export/fish/7')
			.add(AC('gar'))
			.add(AC('rainbow_trout'))
			.add(AC('bayad'))
			.add(AC('piranha'))
			.add(AC('jellyfish'))
			.add(AC('red_grouper'))
			.add(AC('atlantic_cod'))
		event.get('market:export/fish/8')
			.add(AC('muskellunge'))
			.add(AC('pacific_halibut'))
			.add(AC('atlantic_halibut'))
		event.get('market:export/fish/10')
			.add(AC('catfish'))
			.add(AC('capitaine'))
			.add(AC('tuna'))
			.add(AC('arapaima'))
			.add(AC('#turtle'))
			.add(AC('goldfish'))
		event.get('market:export/fishing')
			.add('#market:export/fish/1')
			.add('#market:export/fish/3')
			.add('#market:export/fish/5')
			.add('#market:export/fish/7')
			.add('#market:export/fish/8')
			.add('#market:export/fish/10')
			.add('kubejs:profession_card_fishing')

		event.get('market:export/smithing')
			.add(MC('iron_sword'))
			.add(MC('iron_helmet'))
			.add(MC('iron_chestplate'))
			.add(MC('iron_leggings'))
			.add(MC('iron_boots'))
			.add(MC('golden_sword'))
			.add(MC('golden_chestplate'))
			.add(MC('golden_helmet'))
			.add(MC('golden_leggings'))
			.add(MC('golden_boots'))
			.add(MC('golden_apple'))
			.add(KJ('#casts'))
			.add(MC('#arrows'))
			.add('kubejs:profession_card_smithing')

		event.get('market:export')
			.add('#market:export/farming')
			.add('#market:export/carpentry')
			.add('#market:export/mining')
			.add('#market:export/masonry')
			.add('#market:export/hunting')
			.add('#market:export/cooking')
			.add('#market:export/fishing')
			.add('#market:export/smithing')
			.add('thermal:machine_press')
			.add('thermal:silver_coin')
			.add('thermal:gold_coin')
	//Dome!

	event.get('create:upright_on_belt')
		.add(AE2("red_paint_ball"))
		.add(AE2("yellow_paint_ball"))
		.add(AE2("green_paint_ball"))
		.add(AE2("blue_paint_ball"))
		.add(AE2("magenta_paint_ball"))
		.add(AE2("black_paint_ball"))
		
	//Items in the treasure tags are given as loot from treasure pots
	event.get("kubejs:treasure1")
		.add(MC('cobweb'))
		.add(MC('dandelion'))
		.add(MC('poppy'))
		.add(MC('jungle_sapling'))
		.add(MC('brown_mushroom'))
		.add(MC('red_mushroom'))
		.add(MC('bamboo'))
		.add(MC('ladder'))
		.add(MC('chain'))
		.add(MC('flower_pot'))
		.add(MC('painting'))
		.add(MC('iron_nugget'))
		.add(MC('gold_nugget'))
		.add(CR('copper_nugget'))
		.add(CR('zinc_nugget'))
		.add(MC('charcoal'))
		.add(MC('rotten_flesh'))
		.add(MC('pumpkin_seeds'))
		.add(MC('melon_seeds'))
		.add(MC('bone_meal'))
		.add(MC('paper'))
		.add(FD('raw_pasta'))
		.add(AP('algal_blend'))
		.add(FD('tree_bark'))
		.add(CR('cogwheel'))
		.add(KJ('sky_slimy_fern_leaf'))
		.add(KJ('earth_slimy_fern_leaf'))
		.add(KJ('ender_slimy_fern_leaf'))
		.add(TE('rubber'))
		.add(TE('phytogro'))
		.add(CR('andesite_alloy'))
		.add(MC('poisonous_potato'))

	event.get("kubejs:treasure2")
		.add(MC('lantern'))
		.add(MC('redstone'))
		.add(MC('bow'))
		.add(FD('rice'))
		.add(SP('copper_lantern'))
		.add(SP('brass_lantern'))
		.add(SP('sconce'))
		.add(SP('rope_arrow'))
		.add(SP('slingshot'))
		.add(SP('flax_seeds'))
		.add(SP('bomb'))
		.add(FD('sweet_berry_cookie'))
		.add(FD('cabbage_seeds'))
		.add(FD('tomato_seeds'))
		.add(MC('scute'))
		.add(MC('iron_ingot'))
		.add(MC('copper_ingot'))
		.add(CR('zinc_ingot'))
		.add(TE('rosin'))
		.add(MC('spider_eye'))
		.add(MC('nether_brick'))
		.add(MC('beetroot_seeds'))
		.add(MC('book'))
		.add(MC('name_tag'))
		.add(FD('rope'))
		.add(CR('cinder_flour'))
		.add(TC('seared_brick'))
		.add(FD('canvas'))
		.add(TE('cinnabar'))
		.add(TE('sulfur'))
		.add(TE('niter'))
		.add(TE('apatite'))
		.add(MC('compass'))
		.add(MC('experience_bottle'))
		.add(MC('golden_carrot'))
		//.add('antiqueatlas:empty_antique_atlas')

	//Treasure3 is only given from quartz pots
	event.get("kubejs:treasure3")
		.add(MC('skeleton_skull'))
		.add(MC('clock'))
		.add(MC('diamond'))
		.add(MC('lapis_lazuli'))
		.add(MC('zombie_head'))
		.add(CR('rose_quartz'))
		.add(CR('brass_hand'))
		.add(MC('saddle'))
		.add(AE2('certus_quartz_crystal'))
		.add(AE2('fluix_crystal'))
		.add(TE('ice_charge'))
		.add(TE('lightning_charge'))
		.add(TE('earth_charge'))
		.add(PR_C('red_ingot'))
		.add(TE('ruby'))
		.add(TE('sapphire'))
		.add(CR('peculiar_bell'))
		.add(MC('spectral_arrow'))
		.add(MC('gold_ingot'))
		.add(MC('magma_cream'))
		.add(MC('ghast_tear'))
		.add(MC('quartz'))
		.add(MC('prismarine_shard'))
		.add(MC('prismarine_crystals'))
		.add(MC('chorus_fruit'))
		.add(MC('blaze_powder'))

	event.get('kubejs:ore_processing/metal/dusts')
		.add('#forge:dusts/copper')
		.add('#forge:dusts/iron')
		.add('#forge:dusts/gold')
		.add('#forge:dusts/zinc')
		.add('#forge:dusts/lead')
		.add('#forge:dusts/nickel')

	//This tag auto adds the beacon_payment_items tag which we don't want
	event.remove(CR('create_ingots'), CR('andesite_alloy'))
})

onEvent('block.tags', event => {
	event.add('minecraft:beacon_base_blocks', 'alloyed:steel_block')
	event.remove('minecraft:beacon_base_blocks', 'thermal:bronze_block')

	//Not sure if anything checks for this block tag but don't want to risk it.
	event.remove('forge:storage_blocks/copper', 'minecraft:cut_copper');

	//I don't know why this isn't wrenchable by default
	event.add("create:wrench_pickup", "minecraft:note_block")

	event.add("create:wrench_pickup", "waterstrainer:strainer_base")

	event.add("create:wrench_pickup", /thermal:machine/)
	event.add("create:wrench_pickup", /thermal:device/)
	event.add("create:wrench_pickup", /thermal:dynamo/)
	event.add("create:wrench_pickup", "thermal:tinker_bench")
	event.add("create:wrench_pickup", "thermal:charge_bench")
	event.add("create:wrench_pickup", "thermal:energy_cell_frame")
	event.add("create:wrench_pickup", "thermal:energy_cell")
	event.add("create:wrench_pickup", "thermal:fluid_cell_frame")
	event.add("create:wrench_pickup", "thermal:fluid_cell")
	event.add("create:wrench_pickup", "thermal:energy_duct")
	event.add("create:wrench_pickup", "thermal:fluid_duct")
	event.add("create:wrench_pickup", "thermal:fluid_duct_windowed")

	event.add("create:wrench_pickup", 'supplementaries:cog_block')
	event.add("create:wrench_pickup", 'supplementaries:relayer')
	event.add("create:wrench_pickup", 'supplementaries:spring_launcher')
	event.add("create:wrench_pickup", 'supplementaries:speaker_block')
	event.add("create:wrench_pickup", 'supplementaries:turn_table')
	//event.add("create:wrench_pickup", 'supplementaries:pulley_block')
	//event.add("create:wrench_pickup", 'supplementaries:hourglass')
	event.add("create:wrench_pickup", 'supplementaries:bellows')
	event.add("create:wrench_pickup", 'supplementaries:clock_block')
	event.add("create:wrench_pickup", 'supplementaries:crystal_display')
	event.add("create:wrench_pickup", 'supplementaries:sconce_lever')
	event.add("create:wrench_pickup", 'supplementaries:crank')
	event.add("create:wrench_pickup", 'supplementaries:wind_vane')
	event.add("create:wrench_pickup", 'supplementaries:faucet')

	event.add("create:wrench_pickup", 'cb_multipart:multipart')

	//I really don't know why these blocks are missing the pressure plate tag
	//All the other pressure plates from quark and forbidden have the tag.
	event.add("minecraft:pressure_plates", 'forbidden_arcanus:polished_darkstone_pressure_plate')
})