JEIEvents.hideItems(event => {
    event.hide(/^sophisticatedstorage:limited.+barrel.+$/)
    event.hide("sophisticatedstorage:copper_barrel")
    event.hide("sophisticatedstorage:copper_chest")
    event.hide("sophisticatedstorage:copper_shulker_box")
    event.hide(/^sophisticatedstorage:.*copper.*tier_upgrade$/)
    event.hide("sophisticatedstorage:stack_upgrade_tier_1_plus")
    event.hide("sophisticatedbackpacks:stack_upgrade_omega_tier")
    event.hide("sophisticatedbackpacks:inception_upgrade")
    event.hide(/xp_pump_upgrade/)

    event.hide(/itemfilters/)

    event.hide("ae2:inscriber")
    event.hide(/ae2:.*_budding_quartz/)
    event.hide("ae2:small_quartz_bud")
    event.hide("ae2:medium_quartz_bud")
    event.hide("ae2:large_quartz_bud")
    event.hide("ae2:quartz_cluster")

    event.hide("architects_palette:withered_bone")

    event.hide("create:sturdy_sheet")
    event.hide("create:unprocessed_obsidian_sheet")

    event.hide(/^createdeco:.*coin/)

    event.hide(/incomplete/)
    event.hide(/kubejs:growing/)
    event.hide(/kubejs:failed/)
    event.hide("kubejs:silver_coin")
    event.hide("kubejs:gold_coin")

    event.hide("decorative_blocks:blockstate_copy_item")

    event.hide("occultism:debug_foliot_lumberjack")
    event.hide("occultism:debug_foliot_transport_items")
    event.hide("occultism:debug_foliot_cleaner")
    event.hide("occultism:debug_foliot_trader")
    event.hide("occultism:debug_djinni_manage_machine")
    event.hide("occultism:debug_djinni_test")
    event.hide("occultism:lighted_air")
    event.hide("occultism:jei_dummy/none")
    event.hide("occultism:jei_dummy/require_sacrifice")
    event.hide("occultism:jei_dummy/require_item_use")

    event.hide("prettypipes:blank_module")

    event.hide("thermal:rs_control_augment")
    event.hide("thermal:side_config_augment")
    event.hide("thermal:press_coin_die")
    event.hide("thermal:press_gear_die")
    event.hide("thermal:press_packing_2x2_die")
    event.hide("thermal:press_packing_3x3_die")
    event.hide("thermal:press_unpacking_die")
    event.hide("thermal:iron_coin")
    event.hide("thermal:copper_coin")
    event.hide("thermal:tin_coin")
    event.hide("thermal:lead_coin")
    event.hide("thermal:nickel_coin")
    event.hide("thermal:netherite_coin")
    event.hide("thermal:bronze_coin")
    event.hide("thermal:constantan_coin")
    event.hide("thermal:invar_coin")
    event.hide("thermal:electrum_coin")
    event.hide("thermal:signalum_coin")
    event.hide("thermal:lumium_coin")
    event.hide("thermal:enderium_coin")
    event.hide("thermal:gold_plate")
    event.hide("thermal:iron_plate")
    event.hide("thermal:copper_plate")
    event.hide("thermal:netherite_plate")
    event.hide("thermal:servo_attachment")
    event.hide("thermal:device_hive_extractor")

    event.hide("cb_microblock:microblock")
    event.hide("ae2:facade")
    event.hide("chiselsandbits:block_bit")

    event.hide("trials:crafter")

    event.hide("aquaculture:wooden_fillet_knife")
    event.hide("aquaculture:stone_fillet_knife")
    event.hide("aquaculture:iron_fillet_knife")
    event.hide("aquaculture:gold_fillet_knife")
    event.hide("aquaculture:diamond_fillet_knife")

    event.hide("functionalstorage:puller_upgrade")
    event.hide("functionalstorage:pusher_upgrade")
    event.hide("functionalstorage:collector_upgrade")

    event.hide("sophisticatedbackpacks:magnet_upgrade")
    event.hide("sophisticatedbackpacks:advanced_magnet_upgrade")
    event.hide("sophisticatedstorage:magnet_upgrade")
    event.hide("sophisticatedstorage:advanced_magnet_upgrade")
    event.hide("sophisticatedstorage:hopper_upgrade")
    event.hide("sophisticatedstorage:advanced_hopper_upgrade")

    event.hide('balancedflight:ascended_flight_ring')
})

JEIEvents.hideFluids(event => {
    event.hide("tconstruct:molten_tin")
})
