#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "create", "alloyed", "createdeco", "createaddition", "createbigcannons", "create_dd", "thermal", "tconstruct", "tmechworks"]

