#Compatability config
#There are enough foods in the base pack to earn the first 10 hearts.
#Then next 10 hearts will need addons like the create food addons and farmer's delight addons.

[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 1
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [15, 30, 45, 60, 75, 95, 115, 135, 155, 175, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = [
		"create_central_kitchen:incomplete_egg_sandwich", "create_central_kitchen:incomplete_chicken_sandwich",
		"create_central_kitchen:incomplete_hamburger", "create_central_kitchen:incomplete_bacon_sandwich",
		"create_central_kitchen:incomplete_mutton_wrap", "create_central_kitchen:incomplete_apple_pie",
		"create_central_kitchen:incomplete_sweet_berry_cheesecake", "create_central_kitchen:incomplete_pumpkin_pie",
		"create_central_kitchen:incomplete_cherry_pie", "create_central_kitchen:incomplete_truffle_pie",
		"create_central_kitchen:incomplete_mulberry_pie", "create_central_kitchen:incomplete_chorus_fruit_pie",
		"create_central_kitchen:incomplete_chorus_flower_pie"]

	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false

