// Create Encased
if (Platform.isLoaded("createcasing")) {
	global.itemBlacklist.push("createcasing:oak_shaft")
	global.itemBlacklist.push("createcasing:spruce_shaft")
	global.itemBlacklist.push("createcasing:birch_shaft")
	global.itemBlacklist.push("createcasing:jungle_shaft")
	global.itemBlacklist.push("createcasing:acacia_shaft")
	global.itemBlacklist.push("createcasing:dark_oak_shaft")
	global.itemBlacklist.push("createcasing:crimson_shaft")
	global.itemBlacklist.push("createcasing:warped_shaft")
	global.itemBlacklist.push("createcasing:glass_shaft")
	global.itemBlacklist.push("createcasing:brass_shaft")
	global.itemBlacklist.push("createcasing:oak_cogwheel")
	global.itemBlacklist.push("createcasing:spruce_cogwheel")
	global.itemBlacklist.push("createcasing:birch_cogwheel")
	global.itemBlacklist.push("createcasing:jungle_cogwheel")
	global.itemBlacklist.push("createcasing:acacia_cogwheel")
	global.itemBlacklist.push("createcasing:dark_oak_cogwheel")
	global.itemBlacklist.push("createcasing:crimson_cogwheel")
	global.itemBlacklist.push("createcasing:warped_cogwheel")
	global.itemBlacklist.push("createcasing:oak_large_cogwheel")
	global.itemBlacklist.push("createcasing:spruce_large_cogwheel")
	global.itemBlacklist.push("createcasing:birch_large_cogwheel")
	global.itemBlacklist.push("createcasing:jungle_large_cogwheel")
	global.itemBlacklist.push("createcasing:acacia_large_cogwheel")
	global.itemBlacklist.push("createcasing:dark_oak_large_cogwheel")
	global.itemBlacklist.push("createcasing:crimson_large_cogwheel")
	global.itemBlacklist.push("createcasing:warped_large_cogwheel")
	
	global.randomiumBlacklist.push("createcasing:creative_cogwheel")
	global.randomiumBlacklist.push("createcasing:mldeg_shaft")
	global.randomiumBlacklist.push("createcasing:processing_chorium")
}
