
#
# Rarity of Repurposed Structures Wells.
# This affects the chances of a well spawning in a chunk.
# The chance of a well generating at a chunk is 1/rarityPerChunk.
# 1 for wells spawning in every chunk and 10000 for no wells.
[Wells]
	#Range: 1 ~ 10000
	badlandsWellRarityPerChunk = 450
	#Range: 1 ~ 10000
	netherWellRarityPerChunk = 250
	#Range: 1 ~ 10000
	snowWellRarityPerChunk = 450
	#Range: 1 ~ 10000
	mossyStoneWellRarityPerChunk = 450
	#Range: 1 ~ 10000
	forestWellRarityPerChunk = 450
	#Range: 1 ~ 10000
	mushroomWellRarityPerChunk = 450

